baize:
  - "docs/baize/**/*"

buy:
  - "docs/buy/**/*"

contact:
  - "docs/contact/*"
  - "docs/en/contact/*"

dak:
  - "docs/dak/**/*"
  - "docs/en/dak/**/*"

dev:
  - "scripts/**/*"
  - ".github/**/*"

dmc:
  - "docs/dmc/**/*"
  - "docs/en/dmc/**/*"

dtx:
  - "docs/dtx/**/*"

ghippo:
  - "docs/ghippo/**/*"
  - "docs/en/ghippo/**/*"

insight:
  - "docs/insight/**/*"

kpanda:
  - "docs/kpanda/**/*"

leopard:
  - "docs/leopard/**/*"

monkey:
  - "docs/monkey/**/*"

news:
  - "docs/news/**/*"

zestu:
  - "docs/zestu/**/*"
  - "docs/en/zestu/**/*"
